; PlatformIO Project Configuration File
; Médaillon — D1 mini (ESP8266) + anneau NeoPixel

[env:d1_mini_lite]
platform = espressif8266
board = d1_mini_lite
framework = arduino
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.10.3
