; Master (Baguette du Chef d'orchestre) — ESP32 DevKit v1
; Point d'accès WiFi + interface web (LittleFS) + coordination ESP-NOW.
;
;   pio run -t upload        firmware
;   pio run -t uploadfs      interface web (contenu de data/)

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
upload_port = COM4
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
	links2004/WebSockets@^2.7.3
	bblanchon/ArduinoJson@^7.2.2
