[platformio]
src_dir = ../balise_esp8266/src

[env:balise_est_esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.10.3
build_flags =
  -DDEBUG_MODE=1
  -DDEVICE_ID=3
  -DDEVICE_NAME=\"Balise_Est\"
  -DBALISE_ESP32=1
  -DLED_PIN=2
  -DBATTERY_PIN=34

